# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='jdb_main_pic',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='jdpt1_pic',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='jdpt2_pic',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='jdpt3_pic',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='jdpt4_pic',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='mate_tel',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='qq',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='want_blance',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='zfb_main_pic',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='colleague_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u540c\u4e8b\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='company_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u516c\u53f8\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u516c\u53f8\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='company_salary',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u85aa\u6c34'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='company_tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u516c\u53f8\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u7236\u4eb2\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='friend_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u670b\u53cb\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='friend_tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u670b\u53cb\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='gjj',
            field=models.BooleanField(default=False, verbose_name='\u516c\u79ef\u91d1\u8ba4\u8bc1'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='jd',
            field=models.BooleanField(default=False, verbose_name='\u4eac\u4e1c\u8ba4\u8bc1'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6bcd\u4eb2\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='tb',
            field=models.BooleanField(default=False, verbose_name='\u6dd8\u5b9d\u8ba4\u8bc1'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='zfb_score_pic',
            field=models.ImageField(blank=True, upload_to='customer/zfb', verbose_name='\u652f\u4ed8\u5b9d\u829d\u9ebb\u4fe1\u7528\u5206\u6570\u9875'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8be6\u7ec6\u4f4f\u5740'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='chsi',
            field=models.BooleanField(default=False, verbose_name='\u5b66\u4fe1\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='maimai',
            field=models.BooleanField(default=False, verbose_name='\u8109\u8109\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mno',
            field=models.BooleanField(default=False, verbose_name='\u8fd0\u8425\u5546\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='rhzx',
            field=models.BooleanField(default=False, verbose_name='\u4eba\u884c\u5f81\u4fe1\u8ba4\u8bc1'),
        ),
    ]
