# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(help_text='\u6240\u5c5e\u516c\u53f8', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='yunhu.CompanyModel', verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(help_text='\u90e8\u95e8\u540d\u79f0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='yunhu.DepartmentModel', verbose_name='\u90e8\u95e8\u540d\u79f0'),
        ),
    ]
