# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.IntegerField(blank=True, choices=[(1, '\u5ba1\u6838\u90e8'), (2, '\u8d22\u52a1\u90e8'), (3, '\u50ac\u6536\u90e8')], help_text='\u90e8\u95e8\u540d\u79f0', null=True, verbose_name='\u90e8\u95e8\u540d\u79f0'),
        ),
    ]
