# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8be6\u7ec6\u4f4f\u5740'),
        ),
    ]
