# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(default=uuid.uuid1, help_text='\u6807\u8bc6\u7801', max_length=255, unique=True, verbose_name='\u6807\u8bc6\u7801'),
        ),
    ]
