# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0002_auto_20171210_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='yunhu.CompanyModel', verbose_name='\u6240\u5c5e\u516c\u53f8'),
            preserve_default=False,
        ),
    ]
