# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0002_auto_20171221_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkwaymodel',
            name='namecode',
            field=models.CharField(default='jd', max_length=50, verbose_name='\u6e20\u9053\u4ee3\u7801'),
            preserve_default=False,
        ),
    ]
