# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0002_auto_20171228_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZxyReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(help_text='\u8d44\u4fe1\u4e91\u62a5\u544a', verbose_name='\u8d44\u4fe1\u4e91\u62a5\u544a')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='\u83b7\u53d6\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='companymodel',
            name='fee',
            field=models.FloatField(default=0.0, help_text='\u6263\u8d39\u6807\u51c6', verbose_name='\u6263\u8d39\u6807\u51c6'),
        ),
        migrations.AlterField(
            model_name='auditmodel',
            name='customer',
            field=models.ForeignKey(help_text='\u5ba2\u6237', on_delete=django.db.models.deletion.CASCADE, related_name='audit_customer', to='yunhu.CustomerModel', verbose_name='\u5ba2\u6237'),
        ),
        migrations.AlterField(
            model_name='auditmodel',
            name='note',
            field=models.TextField(blank=True, help_text='\u5ba1\u6838\u7b14\u8bb0', verbose_name='\u5ba1\u6838\u7b14\u8bb0'),
        ),
        migrations.AlterField(
            model_name='auditmodel',
            name='time',
            field=models.DateTimeField(auto_now=True, help_text='\u5ba1\u6838\u65f6\u95f4', verbose_name='\u5ba1\u6838\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='auditmodel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='\u5ba1\u6838\u4eba', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_user', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6838\u4eba'),
        ),
        migrations.AlterField(
            model_name='channelmodel',
            name='check_ways',
            field=models.ManyToManyField(help_text='\u8ba4\u8bc1\u65b9\u5f0f', related_name='check_way_channels', to='yunhu.CheckWayModel', verbose_name='\u8ba4\u8bc1\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='channelmodel',
            name='company',
            field=models.ForeignKey(help_text='\u6240\u5c5e\u516c\u53f8', on_delete=django.db.models.deletion.CASCADE, related_name='company_channels', to='yunhu.CompanyModel', verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='channelmodel',
            name='identification',
            field=models.CharField(blank=True, help_text='\u6807\u8bc6\u7801', max_length=255, null=True, verbose_name='\u6807\u8bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='checkwaymodel',
            name='name',
            field=models.CharField(help_text='\u540d\u79f0', max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='checkwaymodel',
            name='namecode',
            field=models.CharField(help_text='\u6e20\u9053\u4ee3\u7801', max_length=50, verbose_name='\u6e20\u9053\u4ee3\u7801'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='balance',
            field=models.FloatField(default=0.0, help_text='\u8d26\u6237\u4f59\u989d', verbose_name='\u8d26\u6237\u4f59\u989d'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='check_ways',
            field=models.ManyToManyField(help_text='\u5ba1\u67e5\u65b9\u5f0f', related_name='companys', to='yunhu.CheckWayModel', verbose_name='\u5ba1\u67e5\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='create_time',
            field=models.DateTimeField(auto_now=True, help_text='\u521b\u5efa\u65f6\u95f4', verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='h5_first_background',
            field=models.ImageField(default='img/h5/background1.png', help_text='\u4e3b\u80cc\u666f\u56fe', upload_to='img/h5', verbose_name='\u4e3b\u80cc\u666f\u56fe'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='h5_second_background',
            field=models.ImageField(default='img/h5/background2.png', help_text='\u6b21\u80cc\u666f\u56fe', upload_to='img/h5', verbose_name='\u6b21\u80cc\u666f\u56fe'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='possessor',
            field=models.CharField(help_text='\u6240\u6709\u4eba', max_length=50, verbose_name='\u6240\u6709\u4eba'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='remark',
            field=models.TextField(blank=True, help_text='\u5907\u6ce8', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='status',
            field=models.BooleanField(default=True, help_text='\u542f\u7528', verbose_name='\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='customerlogininfomodel',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='customerlogininfomodel',
            name='login_time',
            field=models.DateTimeField(auto_now=True, help_text='\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='address',
            field=models.CharField(blank=True, help_text='\u8be6\u7ec6\u4f4f\u5740', max_length=255, null=True, verbose_name='\u8be6\u7ec6\u4f4f\u5740'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='audit_status',
            field=models.IntegerField(choices=[(1, '\u5f85\u5ba1\u6838'), (2, '\u62d2\u7edd\u53d7\u7406'), (3, '\u5ba1\u6838\u901a\u8fc7'), (4, '\u9700\u8981\u590d\u5ba1'), (5, '\u5df2\u653e\u6b3e'), (6, '\u7eed\u671f'), (7, '\u7ed3\u6e05'), (8, '\u903e\u671f'), (9, '\u50ac\u6536'), (10, '\u50ac\u6536\u7ed3\u6e05')], default=1, help_text='\u5ba1\u6838\u72b6\u6001', verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='blcak_reason',
            field=models.TextField(blank=True, help_text='\u62c9\u9ed1\u539f\u56e0', null=True, verbose_name='\u62c9\u9ed1\u539f\u56e0'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='channel',
            field=models.ForeignKey(help_text='\u6e20\u9053', on_delete=django.db.models.deletion.CASCADE, related_name='customer_channel', to='yunhu.ChannelModel', verbose_name='\u6e20\u9053'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='chsi',
            field=models.BooleanField(default=False, help_text='\u5b66\u4fe1\u8ba4\u8bc1', verbose_name='\u5b66\u4fe1\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='colleague_name',
            field=models.CharField(blank=True, help_text='\u540c\u4e8b\u59d3\u540d', max_length=50, verbose_name='\u540c\u4e8b\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='colleague_tel',
            field=models.CharField(blank=True, help_text='\u540c\u4e8b\u7535\u8bdd', max_length=50, verbose_name='\u540c\u4e8b\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='company_address',
            field=models.CharField(blank=True, help_text='\u516c\u53f8\u5730\u5740', max_length=50, verbose_name='\u516c\u53f8\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='company_name',
            field=models.CharField(blank=True, help_text='\u516c\u53f8\u540d\u79f0', max_length=50, verbose_name='\u516c\u53f8\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='company_salary',
            field=models.CharField(blank=True, help_text='\u85aa\u6c34', max_length=50, verbose_name='\u85aa\u6c34'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='company_tel',
            field=models.CharField(blank=True, help_text='\u516c\u53f8\u7535\u8bdd', max_length=50, verbose_name='\u516c\u53f8\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='\u7533\u8bf7\u65f6\u95f4', verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='father_name',
            field=models.CharField(blank=True, help_text='\u7236\u4eb2\u59d3\u540d', max_length=50, verbose_name='\u7236\u4eb2\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='father_tel',
            field=models.CharField(blank=True, help_text='\u7236\u4eb2\u7535\u8bdd', max_length=50, verbose_name='\u7236\u4eb2\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='friend_name',
            field=models.CharField(blank=True, help_text='\u670b\u53cb\u59d3\u540d', max_length=50, verbose_name='\u670b\u53cb\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='friend_tel',
            field=models.CharField(blank=True, help_text='\u670b\u53cb\u7535\u8bdd', max_length=50, verbose_name='\u670b\u53cb\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='gjj',
            field=models.BooleanField(default=False, help_text='\u516c\u79ef\u91d1\u8ba4\u8bc1', verbose_name='\u516c\u79ef\u91d1\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='jd',
            field=models.BooleanField(default=False, help_text='\u4eac\u4e1c\u8ba4\u8bc1', verbose_name='\u4eac\u4e1c\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='maimai',
            field=models.BooleanField(default=False, help_text='\u8109\u8109\u8ba4\u8bc1', verbose_name='\u8109\u8109\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mno',
            field=models.BooleanField(default=False, help_text='\u8fd0\u8425\u5546\u8ba4\u8bc1', verbose_name='\u8fd0\u8425\u5546\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mother_name',
            field=models.CharField(blank=True, help_text='\u6bcd\u4eb2\u59d3\u540d', max_length=50, verbose_name='\u6bcd\u4eb2\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mother_tel',
            field=models.CharField(blank=True, help_text='\u6bcd\u4eb2\u7535\u8bdd', max_length=50, verbose_name='\u6bcd\u4eb2\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='rhzx',
            field=models.BooleanField(default=False, help_text='\u4eba\u884c\u5f81\u4fe1\u8ba4\u8bc1', verbose_name='\u4eba\u884c\u5f81\u4fe1\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='tb',
            field=models.BooleanField(default=False, help_text='\u6dd8\u5b9d\u8ba4\u8bc1', verbose_name='\u6dd8\u5b9d\u8ba4\u8bc1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='tel',
            field=models.CharField(blank=True, help_text='\u7535\u8bdd', max_length=50, null=True, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='wechat',
            field=models.CharField(blank=True, help_text='\u5fae\u4fe1', max_length=50, null=True, verbose_name='\u5fae\u4fe1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='zfb_manage_pic',
            field=models.ImageField(blank=True, help_text='\u652f\u4ed8\u5b9d\u7ba1\u7406\u9875', upload_to='customer/zfb', verbose_name='\u652f\u4ed8\u5b9d\u7ba1\u7406\u9875'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='zfb_score_pic',
            field=models.ImageField(blank=True, help_text='\u652f\u4ed8\u5b9d\u829d\u9ebb\u4fe1\u7528\u5206\u6570\u9875', upload_to='customer/zfb', verbose_name='\u652f\u4ed8\u5b9d\u829d\u9ebb\u4fe1\u7528\u5206\u6570\u9875'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='zhima_score',
            field=models.CharField(blank=True, help_text='\u829d\u9ebb\u4fe1\u7528\u5206', max_length=50, verbose_name='\u829d\u9ebb\u4fe1\u7528\u5206'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='zone',
            field=models.CharField(blank=True, help_text='\u6240\u5728\u5730\u533a', max_length=50, null=True, verbose_name='\u6240\u5728\u5730\u533a'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='amount',
            field=models.FloatField(help_text='\u6d88\u8d39\u91d1\u989d', verbose_name='\u6d88\u8d39\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='create_time',
            field=models.DateTimeField(auto_now=True, help_text='\u6d88\u8d39\u65f6\u95f4', verbose_name='\u6d88\u8d39\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='detail',
            field=models.TextField(help_text='\u6d88\u8d39\u8bf4\u660e', verbose_name='\u6d88\u8d39\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='user',
            field=models.ForeignKey(help_text='\u6d88\u8d39\u7528\u6237', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d88\u8d39\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='lonasmodel',
            name='customer',
            field=models.ForeignKey(help_text='\u5ba2\u6237', on_delete=django.db.models.deletion.CASCADE, related_name='lona_customer', to='yunhu.CustomerModel', verbose_name='\u5ba2\u6237'),
        ),
        migrations.AlterField(
            model_name='lonasmodel',
            name='lona_time',
            field=models.DateField(auto_now=True, help_text='\u653e\u6b3e\u65f6\u95f4', verbose_name='\u653e\u6b3e\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='lonasmodel',
            name='note',
            field=models.TextField(blank=True, help_text='\u653e\u6b3e\u7b14\u8bb0', verbose_name='\u653e\u6b3e\u7b14\u8bb0'),
        ),
        migrations.AlterField(
            model_name='lonasmodel',
            name='refund_time',
            field=models.DateField(auto_now=True, help_text='\u8fd8\u6b3e\u65f6\u95f4', verbose_name='\u8fd8\u6b3e\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='telcheckmodel',
            name='code',
            field=models.CharField(help_text='\u9a8c\u8bc1\u7801', max_length=50, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
        migrations.AlterField(
            model_name='telcheckmodel',
            name='create_time',
            field=models.DateTimeField(auto_now=True, help_text='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='telcheckmodel',
            name='tel',
            field=models.CharField(help_text='\u624b\u673a\u53f7', max_length=11, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='urgemodel',
            name='customer',
            field=models.ForeignKey(help_text='\u5ba2\u6237', on_delete=django.db.models.deletion.CASCADE, related_name='urge_customer', to='yunhu.CustomerModel', verbose_name='\u5ba2\u6237'),
        ),
        migrations.AlterField(
            model_name='urgemodel',
            name='note',
            field=models.TextField(blank=True, help_text='\u50ac\u6b3e\u7b14\u8bb0', verbose_name='\u50ac\u6b3e\u7b14\u8bb0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(help_text='\u8d1f\u8d23\u6e20\u9053', related_name='channels_users', to='yunhu.ChannelModel', verbose_name='\u8d1f\u8d23\u6e20\u9053'),
        ),
        migrations.AddField(
            model_name='zxyreportmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zxy_report', to='yunhu.CustomerModel'),
        ),
    ]
