# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0003_channelmodel_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
