# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0003_checkwaymodel_namecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(related_name='channels_users', to='yunhu.ChannelModel', verbose_name='\u8d1f\u8d23\u6e20\u9053'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(help_text='\u6240\u5c5e\u516c\u53f8', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comany_users', to='yunhu.CompanyModel', verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
    ]
