# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0004_channelmodel_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='\u542f\u7528'),
        ),
    ]
