# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0004_auto_20171223_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditmodel',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u5ba1\u6838\u65f6\u95f4'),
        ),
    ]
