# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0005_auto_20171210_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='tel',
        ),
    ]
