# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0005_auto_20171202_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='h5_first_background',
            field=models.ImageField(default='static/h5/background.png', upload_to=b'', verbose_name='\u4e3b\u80cc\u666f\u56fe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='h5_second_background',
            field=models.ImageField(default='static/h5/background.png', upload_to=b'', verbose_name='\u4e3b\u80cc\u666f\u56fe'),
            preserve_default=False,
        ),
    ]
