# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0006_auto_20171203_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='h5_first_background',
            field=models.ImageField(default='static/h5/background.png', upload_to='static/img/h5', verbose_name='\u4e3b\u80cc\u666f\u56fe'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='h5_second_background',
            field=models.ImageField(default='static/h5/background.png', upload_to='static/img/h5', verbose_name='\u6b21\u80cc\u666f\u56fe'),
        ),
    ]
