# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0006_remove_companymodel_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='check_ways',
            field=models.ManyToManyField(related_name='check_way_channels', to='yunhu.CheckWayModel', verbose_name='\u8ba4\u8bc1\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='channelmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_channels', to='yunhu.CompanyModel', verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
    ]
