# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0007_auto_20171203_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='idcard_backpic',
            field=models.ImageField(blank=True, help_text='\u8eab\u4efd\u8bc1\u53cd\u9762', null=True, upload_to='static/img/idcard', verbose_name='\u8eab\u4efd\u8bc1\u53cd\u9762'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='idcard_people_pic',
            field=models.ImageField(blank=True, help_text='\u624b\u6301\u8eab\u4efd\u8bc1', null=True, upload_to='static/img/idcard', verbose_name='\u624b\u6301\u8eab\u4efd\u8bc1'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='idcard_pic',
            field=models.ImageField(blank=True, help_text='\u8eab\u4efd\u8bc1\u6b63\u9762', null=True, upload_to='static/img/idcard', verbose_name='\u8eab\u4efd\u8bc1\u6b63\u9762'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='h5_first_background',
            field=models.ImageField(default='static/img/h5/background.png', upload_to='static/img/h5', verbose_name='\u4e3b\u80cc\u666f\u56fe'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='h5_second_background',
            field=models.ImageField(default='static/img/h5/background.png', upload_to='static/img/h5', verbose_name='\u6b21\u80cc\u666f\u56fe'),
        ),
    ]
