# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0007_auto_20171227_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lonasmodel',
            name='refund_time',
            field=models.DateTimeField(blank=True, help_text='\u9ed8\u8ba47\u5929', verbose_name='\u8fd8\u6b3e\u65f6\u95f4'),
        ),
    ]
