# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunhu', '0008_auto_20171203_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelmodel',
            options={'verbose_name': '\u6e20\u9053\u4fe1\u606f', 'verbose_name_plural': '\u6e20\u9053\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='companymodel',
            options={'verbose_name': '\u516c\u53f8\u4fe1\u606f', 'verbose_name_plural': '\u516c\u53f8\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='departmentmodel',
            options={'verbose_name': '\u90e8\u95e8\u4fe1\u606f', 'verbose_name_plural': '\u90e8\u95e8\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='companymodel',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='\u8d26\u6237\u4f59\u989d'),
        ),
    ]
